version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    networks:
      docker-elk:
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    networks:
      docker-elk:
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
networks:
  docker-elk:
    driver: bridge
